const KEY='careerPlayer';
const defaultAttrs={pace:65,shooting:60,passing:62,dribbling:64,defending:45,physical:60,stamina:65,strength:55,vision:60,finishing:58,ballControl:65,tackling:40,interceptions:38,composure:55,reactions:60,weakFoot:3,skillMoves:3};
function getPlayer(){try{return JSON.parse(localStorage.getItem(KEY))}catch(e){return null}}
function savePlayer(p){localStorage.setItem(KEY,JSON.stringify(p));return p}
function clamp(n,a=1,b=99){return Math.max(a,Math.min(b,Math.round(Number(n)||0)))}
function calcOverall(p){const a=p.attributes||defaultAttrs;const pos=p.position||'ST';const groups={GK:['reactions','composure'],CB:['defending','physical','strength','interceptions','tackling'],LB:['pace','defending','stamina','passing'],RB:['pace','defending','stamina','passing'],CM:['passing','vision','stamina','dribbling','physical'],CAM:['passing','vision','dribbling','shooting','ballControl'],LW:['pace','dribbling','shooting','passing','finishing'],RW:['pace','dribbling','shooting','passing','finishing'],ST:['shooting','finishing','pace','physical','composure']};const keys=groups[pos]||groups.ST;return clamp(keys.reduce((s,k)=>s+(a[k]||50),0)/keys.length,40,99)}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0)}
function ensurePlayer(){let p=getPlayer();if(!p){p={name:'بازیکن من',age:18,nationality:'ایران',position:'ST',foot:'راست',club:'باشگاه آزاد',league:'Career League',season:'2026/27',attributes:{...defaultAttrs},fitness:90,sharpness:70,fatigue:10,morale:80,popularity:50,value:500000,salary:10000,contractYears:3,appearances:0,goals:0,assists:0,trophies:0};p.overall=calcOverall(p);savePlayer(p)}return p}
function nav(active){return `<nav class="nav"><a href="career.html" class="${active==='career'?'active':''}">🏠 کریر</a><a href="player.html" class="${active==='player'?'active':''}">👤 بازیکن</a><a href="training.html" class="${active==='training'?'active':''}">🏋️ تمرین</a><a href="match.html" class="${active==='match'?'active':''}">⚽ مسابقه</a><a href="transfers.html" class="${active==='transfers'?'active':''}">🔄 نقل‌وانتقالات</a><a href="contract.html" class="${active==='contract'?'active':''}">📝 قرارداد</a><a href="trophies.html" class="${active==='trophies'?'active':''}">🏆 افتخارات</a><a href="news.html" class="${active==='news'?'active':''}">📰 اخبار</a></nav>`}
function shell(title,active,body){return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Career Football</title><link rel="stylesheet" href="style.css"></head><body><div class="app"><header><div><b class="logo">CAREER FOOTBALL</b><small>فصل 2026/27</small></div></header>${nav(active)}<main>${body}</main><footer>Career Football © 2026</footer></div></body></html>`}
window.CF={getPlayer,savePlayer,calcOverall,money,clamp,ensurePlayer,nav,shell,defaultAttrs};